org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version_range=26.1.2.84

mod_id=starcatcher
mod_name=Starcatcher
mod_license=MIT
mod_version=3.1.2-NEOFORGE-26.1.2
mod_group_id=com.wdiscute.echoes
mod_authors=wdiscute, Nikdo53, ScribbleDemon, DayTheMagpie, Spring, Kapitencraft, DuckXYZ, Identidade470, HappyMeek
