modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="https://discord.gg/WsuFsGSegD" #optional

[[mods]] #mandatory
modId="starcatcher"
version="${mod_version}"
displayName="${mod_name}"
displayURL="http://curseforge.com/minecraft/mc-mods/starcatcher"
logoFile = "icon.png"
mod_authors="${mod_authors}" #optional
description='''A fishing mod with lots of fishes to collect!

Credits:
wdiscute - Main Developer
Kapitenft, DuckXYZ, Nikdo53, Quarris & more - Coding support and fixing my mess
Nikdo53 - Fishing minigame art & miscellaneous texture tweeks
ScribbleDemon - Guide book, Fish radar and "Fish Caught!" notification art
DayTheMagpie - Trophy Models, Tournament UI & models, Secret Notes art, Fisherman's Hats, Selling Bin UI, Bobbers Models, & various other Items and UI art
Spring - 3D Fish models and some item sprite tweaks
Redeix - Icy minigame tank texture, Selling Bin model, Tackle Box model and animations, Farmer's delight food sprites, and several item textures
Identidade470 - Conches & Clams textures and models
Burning Sulphur - Aiding in adding compatibility with mods
Axtro - Help with Farmer's Delight Addon, and Curios support.
HappyMeek - Miscellaneous Bobbers & Hooks Sprites
Monachrome - Create-themed fish item sprites

Thank you to all the translators who contribuited their time to make the mod accessible to everyone! If you'd like to translate reach out to me on discord!

Thank you everyone who stopped by my streams as I developed the mod and followed along the journey ♥
'''

[[mixins]]
config="starcatcher.mixins.json"

# In neoforge.mods.toml:
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.starcatcher]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="AFTER"
side="BOTH"

[[dependencies.starcatcher]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.starcatcher]]
modId = "starcatcher_delight"
type = "optional"
versionRange = "[3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.starcatcher]]
modId = "starcatcher_delight"
type = "incompatible"
versionRange = "[,3.0)"
reason = "Starcatcher requires Starcatcher's Delight v3.0 or newer."
ordering = "NONE"
side = "BOTH"

[[dependencies.starcatcher]]
modId = "scauto"
type = "incompatible"
reason = "No cheating allowed!"

[[dependencies.starcatcher]]
modId="libtooltips"
type="required"
versionRange="[2.3.1,)"
ordering="AFTER"
side="CLIENT"
